#!/bin/sh
set -e

case "$1" in
    remove)
        systemctl stop simbiota.service
        systemctl disable simbiota.service
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
exit 0