[package]
name = "simbiota-monitor"
version = "0.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
crossbeam-channel = "0.5.8"
libc = "0.2.139"
log = "0.4.19"
