name: Package CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: rust:1.70

    steps:
    - uses: actions/checkout@v3

    - name: dependencies
      run: |
        apt-get update
        apt-get install -y openssh-client gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu fakeroot python3-sphinx python3-pip
        pip3 install myst-parser
        rustup target add aarch64-unknown-linux-gnu
        rustup target add armv7-unknown-linux-gnueabihf
       
    
    - name: SSH setup and build
      env:
        TLSH_KEY : ${{secrets.DEPLOY_TLSH}}
        DATABASE_KEY: ${{secrets.DEPLOY_DATABASE}}
      run: |
        cat > ssh_wrap.sh <<- EOF
        #!/bin/bash
        set -x
        for last in \$@; do :; done
        key_file=\$(mktemp -u)
        trap "rm -f \$key_file" EXIT
        eval last=\$last
        ssh-add -L | grep --max-count=1 \$last > \$key_file
        ssh -i \$key_file -o StrictHostKeyChecking=no "\$@"
        EOF
        cat ssh_wrap.sh
        eval `ssh-agent -s`
        echo "Adding SSH key1"
        echo "$DATABASE_KEY" > database_key
        chmod 600 database_key
        ssh-add -v database_key
        echo "Adding SSH key2"
        echo "$TLSH_KEY" > tlsh_key
        chmod 600 tlsh_key
        ssh-add -v tlsh_key
        echo "SSH identities added"
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-add -L
        chmod +x ssh_wrap.sh
        export GIT_SSH="`pwd`/ssh_wrap.sh"
        make package profile=release
    
    - name: Upload arm64 package
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: ARM64 package
        # A file, directory or wildcard pattern that describes what to upload
        path: package/*arm64*.deb
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error
        
    - name: Upload armv7 package
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: ARMv7 package
        # A file, directory or wildcard pattern that describes what to upload
        path: package/*armv7*.deb
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error
